
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"
    token:
      secure: "4f+0Qa5Sg5FVD6ykQDH6/IfAPHXo3uk7kJZdegZTo6s01Kno02gAOxKl5fFv/8CM/lbeOZ4TKrEOVl4aTU/xLUl67DxIY5v0KxKeC4SIifuKgMh9AHD5Eyg7tBIZ0WL7sqgBHW+Q78IgnGBEKZgq2HQFUOqNokPS60w0DaM3IpIcG7MN7/aXdMQ6WBdWNWs0NFFtdmGOjYdXzz5rRII5NTjlHykylowCA9rLL9lvmBqsB7vmAU2BdY1+jmNSCXrb05wYbEoS1I62jLH/KY7IsM9jEX+coH7GYbwghcCA457YgGq6G9xEcvAKT2/gnp/OYOT0u+L+ecSPCaalmUK0jZFvvaX4xOKbPJDb/BSscB9PXYy4VDWFCpP5simH/m2IH3JOx3g2xiIgEqK0tklk8Wjk73v62PGQhHzdr1uIsLD4O7KNkCQ2KR2ZluKqn5KT/OszfAzvm3AVObifbc5SLG0Vj3LxlqKXEB1uxn5jPDxTkoraKBxVgO5TLdimUIUr5CeugwlqmcvN0xmaiV0CI9PYVo7dxWYlM7JBVoUkgwEn0bNL5BKfvE9JJSsOESNip/Y1bR2WRc8WcKX9aMwb9tF7goTqBAlJF4uNx6BEx0XbNDxJ9vUlLSGsfqR3AamCfoetPrHYIr+jAe+V873oJWh0PeTcnHVDuuzgtajP3xc="
      secure: "E/Sg4CnCdcLyiFMofwM2qYNwbLKRaZhFp35IGMZOtrXEhtlnFl+uvdhMFWjGYEHBOO+sfCODH8IzdVtu7ax2fnJFIdzoXqW4dn7pOQXUJacvSHJAYQqZ8LBe47xmM68mWLZqs0bPsEVAEZ2DXlB7ggcM+u9cxoZdowkI1ikBZzOFWoeH12VxT7YaWOLIxNGvFKlhdjPj7oFoGR8CFI3A2QrKT8730nwB2Dcot8PPbsx9KaXpIOLHdh4y3va85gvrWcAvUIHgPKPkkYYg3QN4j+KSvHbKcyKFNDXOqIIT4aMbWt4cKabB7KlvfH3Sut7bctGvvJ/YC1fjZ3ilKOG+ogKw5n4jmohHAkGdvpOrGiHRJ+L3nY1mYuODkE4yWkZ9Iv/O5PxCP14+FLyQFMINMpi8mzpbIn/60FoRhzsKy46IDAhflQjKParovBa3gAzItSYqsdZyyuVPQ9fwlWm8sgo6QZHMOar1rVkns2oA9KTKWRX4CZML0p1jMKC3zoMIAo33m/85oT8WDXTsCrExeAY9jY+GQpX4sQ9EVAuXyhefRkz5dEfn3v5sQVQayKMg1f92EqMy5NKL1nTpAPIid5LeBsgcaeUSC3Om48awYXyruQ2jEyJPUWYjpUQiUwRI/AbazXtZKYlXolk6BW/vPwpSQ877ER22U7OcdJO972g="


script:
 - autoreconf --force --install
 - ./configure
 - sonar-scanner -X

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd

after_success:
 - bash <(curl -s https://codecov.io/bash)
