
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"

before_script:
  - curl -LsS https://nemo.sonarqube.org/static/cpp/build-wrapper-linux-x86.zip > build-wrapper-linux-x86.zip
  - unzip build-wrapper-linux-x86.zip

script:
 - autoreconf --force --install
 - ./configure
 - ./build-wrapper-linux-x86/build-wrapper-linux-x86-64 --out-dir bw_output make clean all
 - sonar-scanner -Dsonar.host.url=https://sonarqube.com -Dsonar.verbose=true -X

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd
 
