
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"
    branches:
     - master
     - restructure

script:
 - autoreconf --force --install
 - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
 - echo "\nsonar.branch=$BRANCH \n" >> ./sonar-project.properties
 - ./configure
 - ./tools/travis-sonarqube.sh
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
 - sonar-scanner -Dsonar.verbose=true -X

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd
 
