
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"
    token:
      secure: "blablablablablablablablablablablabla"


script:
 - autoreconf --force --install
 - ./configure
  - sonar-scanner

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd

after_success:
 - bash <(curl -s https://codecov.io/bash)
