
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"
    token:
      secure: "c0rxYrlzL3CYhC3C1rJxCfCBng8jySoPvGKMoPGSV9AzyMFXlUiCm7pp42VekcBoyg5TcH1TDFwzeh1DQRvWrEcVYmTgP2ZilikKsfoUHbibdgPX0xmnjMPu+zePa3pNVvlLhxRodP6ytjwDxqibI3X95RSXSSRbWMgtSUJia/xi6CE+4Fj+yqbmDZbr8NJL4dhkTxU3VJ8wPhgtzzQ2Aw8zTBMUTrVm8yArQWPRKqBkyNk4Ajso7DHCpHRWRaa6X5guBU7C9jr5IjUmZI8XzhgGV3bPlKlon70g1auGV6nBOV38AXaGizXMtf36B62jaK9x3R05RZHKhscWKb4iD2umAZzJimuS7abETZE5XnrYdTiJSMIz4XsyyjN5w+yXd/gu1/lSv/uT+O4YM/T4OCmUVyPVrIykyMmkFNQyFDpMXtMKV0dTiU6YKLQQqbKNjKa6xZwMe0yXY9vmZlFn2sv+dwTbgaehvgWqMVlpGpwwKGcPPtxqVU5/jkD6yrPRfNWT4Ih7HatLNU1MxkQhHBKIUut0WEjFUCX3gBmFuixIfxQsIvWZhiUHnJ5A7LYJGHU/ndL8vqZmG9UoQsEEGUaThv/XJaTnZ+HCLmveKG24i8LszewVZKXTwyu5icO/kxNbxVtYYVMB6ynP5Vzr8jWKoQcsRSMx3Cx6HKRUu1E="


script:
 - autoreconf --force --install
 - ./configure
 - sonar-scanner -X

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd

after_success:
 - bash <(curl -s https://codecov.io/bash)
