
language: cpp
dist: trusty
sudo: required

jdk:
  - oraclejdk8

addons:
  sonarcloud:
    organization: "uglyoldbob-github"

script:
 - autoreconf --force --install
 - ./configure
 - build-wrapper-linux-x86-64 --out-dir bw-output make clean all
 - sonar-scanner -Dsonar.host.url=https://sonarqube.com -Dsonar.verbose=true -X

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd
 
