
addons:
  apt:
    packages:
      - oracle-java8-installer

language: cpp

install:
 - wget https://github.com/vmt/udis86/archive/v1.7.2.tar.gz
 - tar -xzvf v1.7.2.tar.gz
 - pushd udis86-1.7.2 && ./autogen.sh && popd

deploy:
 provider: script
 script: tools/travis-sonarqube.sh
